### PR TITLE
Frontend game show

### PR DESCRIPTION
**Pull request by rhodesmt**

### CODE REVIEW

**Review by triciasykes — CHANGES_REQUESTED** [review]
is this working in your browser?

**Comment by rhodesmt** [comment]
Yes I can attach a screenshot 
4574C10F-8D6E-4CE3-87BE-749B34A38984
FF7DFB81-2C00-4EA9-830C-C09F9CDC2B68

**Comment by rhodesmt** [comment]
Ok I will make a note of that, thank you!

**Review by triciasykes — APPROVED** [review]
Ok - you just usually need to add conditional rendering on the show.  Just fyi

**Pull request merged**
